version: "3"
services:
  web:
    build: ./backend/
    volumes:
      - "./backend/:/code/"

  server:
    image: nginx:1.20-alpine
    volumes:
      - "./nginx/:/ressources/"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./backend/static/:/static/"
      - "./backend/media/:/media/"
      - "/etc/letsencrypt/live/mkadine.com/fullchain.pem:/letsencrypt/fullchain.pem"
      - "/etc/letsencrypt/live/mkadine.com/privkey.pem:/letsencrypt/privkey.pem"
    ports:
      - 80:80
      - 443:443
