version: "3"
services:
  web:
    build: ./backend/
    volumes:
      - "./backend/:/code/"

  server:
    image: nginx:1.20-alpine
    volumes:
      - "./nginx/:/ressources/"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./letsencrypt/:/letsencrypt/"
      - "./backend/static/:/static/"
      - "./backend/media/:/media/"
    ports:
      - 80:80
      - 443:443
